name: open_file_example
publish_to: none
description: Demonstrates how to use the open_file plugin.
version: 1.0.0+1
environment:
  sdk: ">=3.12.2"

dependencies:
  cupertino_icons: 1.0.9
  flutter:
    sdk: flutter
  better_open_file:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:

  uses-material-design: true
