name: open_file_example
description: Demonstrates how to use the open_file plugin.
version: 1.0.0+1
environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  better_open_file:
    path: ../

flutter:

  uses-material-design: true
